### ISSUE TITLE
WSL Hello error: cannot find the credential public key for this user

### ISSUE THREAD

**Issue by cbryant02** [nullpo-head/WSL-Hello-sudo#3]
Upon running `su -` this error message is printed. No further information is provided either by PAM or WSL-Hello.

The only extra PAM modules loaded for su are `pam_rootok.so` and `pam_wsl_hello.so`.

**Comment by cbryant02** [comment]
It appears this is a problem with [fish](https://fishshell.com/). Resolved.

**Comment by cbryant02** [comment]
Appears to be a problem with fish. Install script didn't complete.

**Comment by jonaskuske** [comment]
For anyone finding this issue:
I thought I had the same problem, but it was a false flag: `sudo` authentication doesn't work, so you enable it for `su` to see errors – but when you're using this script with `su`, it tries to read the public key for `root` (instead of your username), which doesn't exist, so you see this error. But that's `su` specific and an *additional* error, not the actual error you're encountering when you're trying to use `sudo`! (in my case the actual problem was https://github.com/nullpo-head/WSL-Hello-sudo/issues/9)
